@startuml

entity User {

Id: integer <<generated>>
username: varchar(255)
email: varchar(255)
password: varchar(255)

}
entity Tag {
Id: integer <<generated>>
name: varchar(255)

}


entity Article {

Id: integer <<generated>>
title: varchar(255)
bg_media: varchar(255)
content: text

}

entity TutorialPage {
Id: integer <<generated>>

title: varchar(255)
}

entity Media {
Id: integer <<generated>>
title: varchar(255)
description: text
favoriteId: integer <<FK>>
}

entity Favorite {
id: integer <<generated>>
userId: integer <<FK>>
}

entity MediaTag {
  mediaId: integer <<FK>>
  tagId: integer <<Fk>>
}

entity ArticleTag {
  articleId: integer <<FK>>
  tagId: integer <<FK>>
}


entity Category {

Id: integer <<generated>>
bg_color: varchar(255)
name: varchar(255)
bg_image: varchar(255)

}


entity Content_Category {
categoryId: integer <<FK>>
articleId: integer <<FK>>
mediaId: integer <<FK>>
}

entity Help {
id: integer <<generated>>
helptext: text
}

entity Info {
id: integer <<generated>>
infotext: text
}

User "1" -- "*" Favorite : "userId:Id"
Favorite "1" -- "*" Media : "favoriteId:Id"
Favorite "1" -- "*" Article : "favoriteId:Id"
Media "1" -- "*" Content_Category : "mediaId:Id"
Article "1" -- "*" Content_Category: "articleId:Id"
Content_Category "1" -- "*" Category : "categoryId:Id"

(Media,Tag) .. MediaTag: "mediaId:Id, tagId:Id"
(Article,Tag) .. ArticleTag: "articleId:Id, tagId:Id"


@enduml